services:
  halo:
    image: registry.fit2cloud.com/halo/halo:2.17
    restart: on-failure:3
    volumes:
      - ./halo2:/root/.halo2
    ports:
      - "80:8090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://host.docker.internal:8090/actuator/health/readiness"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    command:
      - --spring.r2dbc.url=r2dbc:postgresql://host.docker.internal:5432/halo
      - --spring.r2dbc.username=postgres
      # PostgreSQL 的密码，请保证与下方 POSTGRES_PASSWORD 的变量值一致。
      - --spring.r2dbc.password=jq1mtY4gBa6gIuJrggM=
      - --spring.sql.init.platform=postgresql
      # 外部访问地址，请根据实际需要修改
      - --halo.external-url=http://thinking-progress.com:80/
    extra_hosts:
      - "host.docker.internal:host-gateway"

